# HTML 리포트 생성
test-report:
	pytest --html=reports/shop-backend-api-test-report.html --self-contained-html

# HTML 리포트 생성 (verbose)
test-report-v:
	pytest -v --html=reports/shop-backend-api-test-report.html --self-contained-html