# pytest 설정 파일 (어떻게 실행할지 정의)

[pytest]

# 1. 테스트 분류 (마커 정의)
markers =
    auth: 인증 API 테스트
    order: 주문 API 테스트
    point: 포인트 API 테스트
    health: 헬스 체크 API 테스트
    slow: 상대적으로 실행 시간이 긴 테스트(ex - 동시성 테스트)

# 2. 실행 경로
# tests 폴더에서 테스트 찾기
testpaths = tests

# test_ 로 시작하는 파일을 테스트 파일로 인식
python_files = test_*.py

# test_ 로 시작하는 함수를 테스트 함수로 인식
python_functions = test_*

# verbose 모드 설정 (테스트 결과 자세히 출력)
addopts = -v

# 3. 로그 설정
# pytest 실행 중 로그를 터미널에 출력
log_cli = true

# INFO 레벨 이상의 로그를 출력(DEBUG < INFO < WARNING < ERROR < CRITICAL)
log_cli_level = INFO

# 로그 출력 포맷 지정
log_cli_format = %(asctime)s [%(levelname)s] %(name)s - %(message)s

# 로그 시간 출력 형식
log_cli_date_format = %Y-%m-%d %H:%M:%S
